version: 0.2

phases:
  pre_build:
    commands:
      - cd deploy
      - if [ -e /tmp/node_modules.tar ];then tar xf /tmp/node_modules.tar; fi
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - tar cf /tmp/node_modules.tar node_modules
artifacts:
  files:
    - '**/*'
  base-directory: 'deploy/dist'
cache:
  paths:
    - /tmp/node_modules.tar
